apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: waghepratiksha21/bankapp:latest
        ports:
        - containerPort: 8080
