name: CI-CD pipeline

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.4-eclipse-temurin-17
    steps:
      - uses: actions/checkout@v4

      - name: Build JAR
        run: mvn clean package -DskipTests

  security-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
      - name: Run Trivy Scan
        run: trivy fs .

  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.4-eclipse-temurin-17
    needs: security-check
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: mvn clean test

  sonar-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: sudo apt-get update && sudo apt-get install gitleaks -y

      - name: Run Gitleaks
        run: gitleaks detect --source .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  docker-build:
    runs-on: ubuntu-latest
    needs: sonar-scan
    steps:
      - uses: actions/checkout@v4

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build --progress=plain -t waghepratiksha21/bankapp:latest .

      - name: Push Docker Image
        run: docker push waghepratiksha21/bankapp:latest

  deploy-eks:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install kubectl
        run: |
       curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
       chmod +x kubectl
       sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: |
          echo "EKS Cluster: ${{ secrets.EKS_CLUSTER_NAME }}"
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
